### ISSUE TITLE
Perfmon Counters ASP.NET Apps v4.0.30319

### ISSUE THREAD

**Issue by mvaanand** [newrelic/nri-perfmon#10]
I updated config.json with the following and I'm unable to see ASP.NET Apps v4.0.30319 in the Insights Events:

{
      "provider": "PerfCounter",
      "category": "ASP.NET Apps v4.0.30319",
      "counters": [
        {
          "counter": "Requests Executing"
        },
        {
          "counter": "Requests Failed"
        },
        {
          "counter": "Requests In Application Queue"
        },
        {
          "counter": "Requests Timed Out"
        },
	{
          "counter": "Requests Total"
        },
        {
          "counter": "Request Execution Time"
        },
        {
          "counter": "Request Wait Time"
        }
      ]

These are the Perfmon Counters I'm trying to set up:

\ASP.NET Apps v4.0.30319(__Total__)\Requests Executing
\ASP.NET Apps v4.0.30319(__Total__)\Requests Failed
\ASP.NET Apps v4.0.30319(__Total__)\Requests In Application Queue
\ASP.NET Apps v4.0.30319(__Total__)\Requests Timed Out
\ASP.NET Apps v4.0.30319(__Total__)\Requests Total
\ASP.NET Apps v4.0.30319(__Total__)\Request Execution Time
\ASP.NET Apps v4.0.30319(__Total__)\Request Wait Time

Any help is appreciated.

**Comment by mvaanand** [comment]
I'm seeing the following error:

2019-10-15T17:03:04-04:00" level=error msg="Integration command failed" error="exit status 3762504530" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon stderr="\nUnhandled Exception: System.InvalidOperationException: Could not locate Performance Counter with specified category name 'ASP.NET Apps v4.0.30319', counter name 'Requests Executing, Requests Failed, Requests In Application Queue, Requests Timed Out, Requests Total, Request Execution Time, Request Wait Time'.\r\n   at System.Diagnostics.PerformanceCounter.InitializeImpl()\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)\r\n   at NewRelic.PerfmonQuery..ctor(String pname, String caname, String coname, String iname) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 91\r\n   at NewRelic.PerfmonPlugin.AddCounter(Counterlist aCounter, Int32 whichCounter) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 222\r\n   at NewRelic.PerfmonPlugin..ctor(Options options, List`1 counters) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 148\r\n   at NewRelic.Program.Main(String[] args) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Program.cs:line 120\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"

**Comment by sschwartzman** [comment]
Hi @mvaanand - the counter names are actually different when gotten programmatically from Perfmon. If you run this command at command line, you can see all of the counters for ASPNet: 
```
get-wmiobject -computername localhost -Namespace root\CIMV2 -Query "Select * from Win32_PerfFormattedData_ASPNET_ASPNETApplications"
```

If you take a look at the default config file, it has good examples for ASPNet. I extrapolated what's in there to convert what you sent to what I think should be a valid form. Please try this out:
```
{
  "provider": "ASPNET",
  "category": "ASPNETApplications",
  "counters": [{
      "counter": "ErrorsTotal"
    },
    {
      "counter": "RequestsExecuting"
    },
    {
      "counter": "RequestsFailed"
    },
    {
      "counter": "RequestsInApplicationQueue"
    },
    {
      "counter": "RequestsTimedOut"
    },
    {
      "counter": "RequestsTotal"
    },
    {
      "counter": "RequestExecutionTime"
    },
    {
      "counter": "RequestWaitTime"
    }
  ]
}
```

**Comment by mvaanand** [comment]
get-wmiobject -computername localhost -Namespace root\CIMV2 -Query "Select * from Win32_PerfFormattedData_ASPNET_ASPNETApplications"

The above command returns a zero for all counters.

I had tried that couple days back - when I see the events in the Insights dashboard the data is all zero's.

so I tried the below steps from the readme instructions:

If you specify the provider as PerfCounter, the plugin will retrieve the Windows Performance Counter instead of running a WMI query. This can be useful if WMI is returning "all 0's" in a query or the appropriate Performance Counter is easier to find. Example of usage:
{
	"provider": "PerfCounter",
	"category": "ASP.NET v4.0.30319",
	"counters": [{
		"counter": "Requests Current"
	}]
}

This is not working either.

**Comment by sschwartzman** [comment]
Did you try the replacement for your counters that I provided you above?

**Comment by mvaanand** [comment]
I did and all i see are 0's. If i manually run the perfmon counter collection using perfmon I see the data. WMI query returns all 0's.

**Comment by sschwartzman** [comment]
It may be that perfCounter can only take one counter. When you try just this one, it fails?

```
{
"provider": "PerfCounter",
"category": "ASP.NET Apps v4.0.30319",
"counters": [{
"counter": "Requests Current"
}]
}
```

This is slightly different from the example, I added "Apps" here.

**Comment by mvaanand** [comment]
I get the following error:

"2019-10-17T13:03:40-04:00" level=info msg="Integration health check finished with some errors" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-17T13:03:43-04:00" level=error msg="Integration command failed" error="exit status 3762504530" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon stderr="\nUnhandled Exception: System.InvalidOperationException: Could not locate Performance Counter with specified category name 'ASP.NET Apps v4.0.30319', counter name 'Requests Current'.\r\n   at System.Diagnostics.PerformanceCounter.InitializeImpl()\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, Boolean readOnly)\r\n   at NewRelic.PerfmonQuery..ctor(String pname, String caname, String coname, String iname) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 86\r\n   at NewRelic.PerfmonPlugin.AddCounter(Counterlist aCounter, Int32 whichCounter) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 222\r\n   at NewRelic.PerfmonPlugin..ctor(Options options, List`1 counters) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 148\r\n   at NewRelic.Program.Main(String[] args) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Program.cs:line 120\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-17T13:04:01-04:00" level=error msg="Integration command failed" error="exit status 3762504530" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon stderr="\nUnhandled Exception: System.InvalidOperationException: Could not locate Performance Counter with specified category name 'ASP.NET Apps v4.0.30319', counter name 'Requests Current'.\r\n   at System.Diagnostics.PerformanceCounter.InitializeImpl()\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, Boolean readOnly)\r\n   at NewRelic.PerfmonQuery..ctor(String pname, String caname, String coname, String iname) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 86\r\n   at NewRelic.PerfmonPlugin.AddCounter(Counterlist aCounter, Int32 whichCounter) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 222\r\n   at NewRelic.PerfmonPlugin..ctor(Options options, List`1 counters) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 148\r\n   at NewRelic.Program.Main(String[] args) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Program.cs:line 120\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"
time="2019-10-17T13:04:18-04:00" level=error msg="Integration command failed" error="exit status 3762504530" instance=nri-perfmon-metrics integration=com.newrelic.perfmon prefix=integration/nri-perfmon stderr="\nUnhandled Exception: System.InvalidOperationException: Could not locate Performance Counter with specified category name 'ASP.NET Apps v4.0.30319', counter name 'Requests Current'.\r\n   at System.Diagnostics.PerformanceCounter.InitializeImpl()\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)\r\n   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, Boolean readOnly)\r\n   at NewRelic.PerfmonQuery..ctor(String pname, String caname, String coname, String iname) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 86\r\n   at NewRelic.PerfmonPlugin.AddCounter(Counterlist aCounter, Int32 whichCounter) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 222\r\n   at NewRelic.PerfmonPlugin..ctor(Options options, List`1 counters) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Plugin.cs:line 148\r\n   at NewRelic.Program.Main(String[] args) in Z:\\eclipse\\nri-perfmon\\nri-perfmon\\Program.cs:line 120\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations"

**Comment by sschwartzman** [comment]
I'm fixing up the PerformanceCounter code some to make it more flexible with counters. Please give me a little time (hopefully today or tomorrow but possibly into next week) and I'll get back to you with a binary to test.

**Comment by mvaanand** [comment]
Awesome. Thx Seth.

**Comment by sschwartzman** [comment]
Can you unzip and drop in this exe to see if it works with your original config file (as in, what we started this issue with)?
[nri-perfmon.exe.zip](https://github.com/newrelic/nri-perfmon/files/3741095/nri-perfmon.exe.zip)

Now when it encounters an invalid counter, it will say as much in the log, but not throw an unhandled exception, and other counters that are valid will still run. Also added handling of instances not being listed (it gets all instances when that happens) and use of the '*' for counter gets all counters in that category. Whew!

**Comment by mvaanand** [comment]
This time there are no unhandled exceptions.

ASPNET, ASPNETApplication still return 0's for all counters.

ASP.NET Apps v4.0.30319 doesn't show up in the events. This uses the PerfCounter Provider. 

Attaching config.json and log for your review:
[newrelic-infra.zip](https://github.com/newrelic/nri-perfmon/files/3741329/newrelic-infra.zip)

[config.zip](https://github.com/newrelic/nri-perfmon/files/3741322/config.zip)

**Comment by sschwartzman** [comment]
This shouldn't change the ASPNET and ASPNETApplication counters, if they're getting you 0's that's why we're playing with PerfCounter.

As for the PerfCounter provider, can you run "SHOW EVENT TYPES" in NRQL and paste what it comes back with?

**Comment by mvaanand** [comment]
{
  "results": [
    {
      "eventTypes": [
        "ASPNET",
        "ASPNETApplications",
        "ASPNETStateService",
        "AWSPrice",
        "AdvisorSample",
        "AjaxRequest",
        "AlertsRecentEvents",
        "ApacheSample",
        "Apigee_Http_CheckSample",
        "Apigee_Proc_CheckSample",
        "AppBuildEvent",
        "AutoScalingGroupSample",
        "AutoScalingInstanceSample",
        "AutoScalingLaunchConfigurationSample",
        "AutoScalingPolicySample",
        "AutoScalingRegionLimitSample",
        "BlockDeviceSample",
        "BrowserInteraction",
        "CassandraColumnFamilySample",
        "CassandraSample",
        "CloudwatchSample",
        "ComputeSample",
        "DPCPU",
        "DPConnectionsAccepted",
        "DPHTTPConnections",
        "DPHTTPMeanTransactionTime",
        "DPHTTPTransactions",
        "DPLoadBalancerStatus",
        "DPObjectStatus",
        "DPReceiveKbpsThroughput",
        "DPServicePerformance",
        "DPTransmitKbpsThroughput",
        "DPWSOperationMetrics",
        "DatastoreSample",
        "DnsSample",
        "DuplicatePodIPs",
        "HealthCheckSample",
        "InfrastructureEvent",
        "IntegrationDataFreshnessReport",
        "IntegrationError",
        "IntegrationProviderReport",
        "InternalK8sCompositeSample",
        "JVMApigeeSample",
        "JVMSample",
        "JavaScriptError",
        "JenkinsEvent",
        "K8sClusterSample",
        "K8sContainerSample",
        "K8sDeploymentSample",
        "K8sNamespaceSample",
        "K8sNodeSample",
        "K8sPodSample",
        "K8sReplicasetSample",
        "K8sVolumeSample",
        "KubectlGetNodes",
        "KubectlPluginLogin",
        "LiveChatAck",
        "LoadBalancerSample",
        "MIQ",
        "MSMQQueue",
        "MSMQService",
        "MVBScreenTimes",
        "Metric",
        "Mobile",
        "MobileCrash",
        "MobileRequest",
        "MobileRequestError",
        "MobileSession",
        "NETCLRExceptions",
        "NETCLRInterop",
        "NETCLRJit",
        "NETCLRLoading",
        "NETCLRLocksAndThreads",
        "NETCLRMemory",
        "NetworkPortSample",
        "NetworkSample",
        "NrAuditEvent",
        "NrIntegrationError",
        "NtlsEvents",
        "OracleDatabaseSample",
        "OracleTablespaceSample",
        "PageAction",
        "PageView",
        "PcfFirehoseEvent",
        "PostgresqlDatabaseSample",
        "PostgresqlIndexSample",
        "PostgresqlInstanceSample",
        "PostgresqlTableSample",
        "PrivateNetworkSample",
        "ProcessSample",
        "QueueSample",
        "Relationship",
        "ServerlessSample",
        "SesReceiptSample",
        "SesRegionSample",
        "Span",
        "StorageSample",
        "SyntheticCheck",
        "SyntheticRequest",
        "SyntheticsPrivateLocationStatus",
        "SystemSample",
        "SystemctlStatus",
        "Transaction",
        "TransactionError",
        "TrustedAdvisorSample",
        "VvovOperationsSample",
        "WeaveNetError",
        "WebService",
        "ZookeeperSample",
        "aemjmx",
        "apigee_nonprod_httpSample",
        "apigee_nonprod_processSample",
        "apigee_prod_httpSample",
        "apigee_prod_processSample",
        "cmdb",
        "curlSample",
        "flexStatusSample",
        "otdb",
        "otdb_dev",
        "procSample",
        "unixMonitor:Disk",
        "unixMonitor:DiskIO",
        "unixMonitor:NetworkIO",
        "unixMonitor:Process",
        "unixMonitor:Stats",
        "unixMonitor:Vmstat"
      ]
    }
  ],
  "metadata": {
    "guid": "84801a87-afc3-15af-f328-12ca738ba3ba",
    "routerGuid": "",
    "messages": [],
    "contents": [
      {
        "function": "eventTypes"
      }
    ]
  }
}

[output.zip](https://github.com/newrelic/nri-perfmon/files/3741468/output.zip)

**Comment by sschwartzman** [comment]
Glad I asked for the output! If you look at it, it had one HUGE event for all of the instances - the PerfCounter code wasn't built to split them up into separate events. So, I fixed it - now each instance will have a separate event of the same eventType, but with an attribute called "name" that contains the instance name.

Please try this out (attached zip of exe): [nri-perfmon.exe.zip](https://github.com/newrelic/nri-perfmon/files/3743648/nri-perfmon.exe.zip). I'm pretty confident we'll be good to go after this go-round.

**Comment by mvaanand** [comment]
After I moved in the latest ni-perfmon.exe all of the counters have stopped reporting in the Insights dashboards.  ASPNET & ASPNETApplications custom events show up but I don't see any data. I don't see any errors either. ASP.NET Apps v4.0.30319 still doesn't show up in the insights events.

I'm attaching config.json for your review. Also attached output from manual invocation of nri-perfmon\nri-perfmon.exe.

{
  "results": [
    {
      "eventTypes": [
        "ASPNET",
        "ASPNETApplications",
        "ASPNETStateService",
        "AWSPrice",
        "AdvisorSample",
        "AjaxRequest",
        "AlertsRecentEvents",
        "ApacheSample",
        "Apigee_Http_CheckSample",
        "Apigee_Proc_CheckSample",
        "AppBuildEvent",
        "AutoScalingGroupSample",
        "AutoScalingInstanceSample",
        "AutoScalingLaunchConfigurationSample",
        "AutoScalingPolicySample",
        "AutoScalingRegionLimitSample",
        "BlockDeviceSample",
        "BrowserInteraction",
        "CassandraColumnFamilySample",
        "CassandraSample",
        "CloudwatchSample",
        "ComputeSample",
        "DPCPU",
        "DPConnectionsAccepted",
        "DPHTTPConnections",
        "DPHTTPMeanTransactionTime",
        "DPHTTPTransactions",
        "DPLoadBalancerStatus",
        "DPObjectStatus",
        "DPReceiveKbpsThroughput",
        "DPTransmitKbpsThroughput",
        "DPWSOperationMetrics",
        "DatastoreSample",
        "DnsSample",
        "DuplicatePodIPs",
        "HealthCheckSample",
        "InfrastructureEvent",
        "IntegrationDataFreshnessReport",
        "IntegrationError",
        "IntegrationProviderReport",
        "InternalK8sCompositeSample",
        "JVMApigeeSample",
        "JVMSample",
        "JavaScriptError",
        "JenkinsEvent",
        "K8sClusterSample",
        "K8sContainerSample",
        "K8sDeploymentSample",
        "K8sNamespaceSample",
        "K8sNodeSample",
        "K8sPodSample",
        "K8sReplicasetSample",
        "K8sVolumeSample",
        "KubectlGetNodes",
        "KubectlPluginLogin",
        "LiveChatAck",
        "LoadBalancerSample",
        "MIQ",
        "MSMQQueue",
        "MSMQService",
        "MVBScreenTimes",
        "Metric",
        "Mobile",
        "MobileCrash",
        "MobileHandledException",
        "MobileRequest",
        "MobileRequestError",
        "MobileSession",
        "NETCLRExceptions",
        "NETCLRInterop",
        "NETCLRJit",
        "NETCLRLoading",
        "NETCLRLocksAndThreads",
        "NETCLRMemory",
        "NetworkPortSample",
        "NetworkSample",
        "NrAuditEvent",
        "NrDailyUsage",
        "NrIntegrationError",
        "NtlsEvents",
        "OracleDatabaseSample",
        "OracleTablespaceSample",
        "PageAction",
        "PageView",
        "PcfFirehoseEvent",
        "PostgresqlDatabaseSample",
        "PostgresqlIndexSample",
        "PostgresqlInstanceSample",
        "PostgresqlTableSample",
        "PrivateNetworkSample",
        "ProcessSample",
        "QueueSample",
        "Relationship",
        "ServerlessSample",
        "SesReceiptSample",
        "SesRegionSample",
        "Span",
        "StorageSample",
        "SyntheticAudit",
        "SyntheticCheck",
        "SyntheticRequest",
        "SyntheticsPrivateLocationStatus",
        "SystemSample",
        "SystemctlStatus",
        "Transaction",
        "TransactionError",
        "TrustedAdvisorSample",
        "VvovOperationsSample",
        "WeaveNetError",
        "WebService",
        "ZookeeperSample",
        "aemjmx",
        "apigee_nonprod_httpSample",
        "apigee_nonprod_processSample",
        "apigee_prod_httpSample",
        "apigee_prod_processSample",
        "cmdb",
        "curlSample",
        "flexStatusSample",
        "iaasalert",
        "otdb",
        "otdb_dev",
        "procSample",
        "unixMonitor:Disk",
        "unixMonitor:DiskIO",
        "unixMonitor:NetworkIO",
        "unixMonitor:Process",
        "unixMonitor:Stats",
        "unixMonitor:Vmstat"
      ]
    }
  ],
  "metadata": {
    "guid": "3148cc88-56f5-ea75-752b-e536e5a5506f",
    "routerGuid": "",
    "messages": [],
    "contents": [
      {
        "function": "eventTypes"
      }
    ]
  }
}

[Data.zip](https://github.com/newrelic/nri-perfmon/files/3744227/Data.zip)
[config.zip](https://github.com/newrelic/nri-perfmon/files/3744228/config.zip)

**Comment by sschwartzman** [comment]
Ahh, this is a new issue, not specific to PerfCounter. If you look at the data you sent, it has the events properly split up. The problem is now, there are so many separate instances to report, its hitting the maximums of Insights. So I need to make the OHI split up the events into chunks below those limits. I will let you know what I come up with.

**Comment by sschwartzman** [comment]
You can disregard my last comment :) The fix turned out to be far simpler than that. I had changed "event_type" to "eventType" in the OHI, and that cause all of the events to stop showing up. Once I switched it back, I got my events to re-appear.

Here is a fixed version, please give it a spin. Hopefully this is it!

[nri-perfmon.exe.zip](https://github.com/newrelic/nri-perfmon/files/3744797/nri-perfmon.exe.zip)

**Comment by mvaanand** [comment]
ASPNET & ASPNETApplications custom events show up but the data is all 0's. ASP.NET Apps v4.0.30319 still doesn't show up in the insights events.

**Comment by sschwartzman** [comment]
Can you send me the data again then? And this time, can you send me any infra logs?

**Comment by mvaanand** [comment]
[newrelic-infra.zip](https://github.com/newrelic/nri-perfmon/files/3745328/newrelic-infra.zip)


I do see errors

**Comment by sschwartzman** [comment]
Ok, I figured out why that event type wasn't showing up this time, and my apologies for all of this back-and-forth. Event types cant have '.' in them, and when I was testing, I was using PerfCounters that don't have '.' in the name. So I've updated the code to convert '.' to '_', which is valid for Event type. So THIS time around it should work.

[nri-perfmon.zip](https://github.com/newrelic/nri-perfmon/files/3745385/nri-perfmon.zip)

Please try this out one more time. Ii it doesn't work, let's set up a working session next week to troubleshoot. Again, I'm sorry for having gone through multiple rounds with this, the PerfCounter code hasn't been used much so it was a learning experience for me as well.

Attached also is a screen shot of that event type working on my Win10 VM: ![Insights__Explorer](https://user-images.githubusercontent.com/3536684/67122434-cce13380-f1bb-11e9-9602-c303fad14ab0.png)

**Comment by mvaanand** [comment]
IT WORKS!!!!! TY so much Seth. I'm going to try out other perfmon counters that actually provide data.

There is a minor issue though. When I have to update the exe I have to pretty much stop Infra Agent and then Kill nri-perfmon.exe. Is there a way to include stopping nri-perfmon.exe with the infra agent stop? In addition after installing the perfmon plugin, I get a error pop up every time I stop the Infra Agent. The agent stops though but would be nice to not see the error pop up.

**Comment by sschwartzman** [comment]
I'm SO glad to hear it! I'm going to go ahead and close out this ticket.

I am not having that issue with my Infra agent... is there a chance you're running an older version? I remember that being an issue before (having to kill nri-perfmon.exe) but it's closing out gracefully for me when I stop the Infra service.

**Comment by sschwartzman** [comment]
@mvaanand I know this issue is resolved but just an update on the "minor issue" you saw. It turns out there was a regression in the Infra agent on Windows, such that when started/stopped as a service, it didn't close out long-running integrations like nri-perfmon. As of v1.7.6 of the Infastructure agent, that is fixed! I tested it on my Windows 10 VM just now, in fact.

https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-176

Happy monitoring!

--Seth

**Comment by mvaanand** [comment]
Thanks for the update. I installed v1.7.6 and I no longer see the issue with the recycle.

I have a specific label in the newrelic-infra.yml

custom_attributes:
  environment: Frontend

I'm able to lookup by the label name in the infra dashboard. 

Specifically as part of the Perfmon data, there is a label in the Insights dashboard that has "Production" as the only value. I'm not sure where that comes from but is there a way to push custom labels from newrelic-infra.yml into insights?

**Comment by sschwartzman** [comment]
I can't speak on behalf of where that "Label.Envrionment" attribute is being set, but I believe you're looking for this?

https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure/configuration/infrastructure-configuration-settings#custom-attributes

When I added custom attributes like below to newrelic-infra.yml, they showed up in Infrastructure, as well as in all of the events from the Perfmon OHI:

```
license_key: (redacted)
verbose: 0
log_file: c:\temp\nria.log
custom_attributes:
  testing: seth-test
```
Here's what it looks like in Infrastructure:

![Infrastructure_by_New_Relic](https://user-images.githubusercontent.com/3536684/70329573-ba719680-1809-11ea-8ead-e7a094d18b2d.png)

Here's what it looks like in Insights. This is the "ASPNET" event created by the Perfmon OHI:

<img width="1076" alt="Insights__Explorer" src="https://user-images.githubusercontent.com/3536684/70329656-e68d1780-1809-11ea-8aaf-cd1899c709f6.png">

**Comment by mvaanand** [comment]
I'm now able to see the labels. Was a mistake in the  newrelic-infra.yml.

Appreciate your help as always Seth.

Thanks,

Vijay Anand Manjamuthu.

*VCM IT - **DEVOPS* *-* *R**etail **A**pplication **S**upport.*

RAS ALL (ras.all@verizon.com) – 24x7

**Comment by mvaanand** [comment]
What does the config.json look like for these perfmon counters:

\.NET CLR Memory(w3wp)\# Gen 0 Collections
\.NET CLR Memory(w3wp)\# Gen 1 Collections
\.NET CLR Memory(w3wp)\# Gen 2 Collections
\.NET CLR Memory(w3wp)\Gen 0 heap size
\.NET CLR Memory(w3wp)\Gen 1 heap size
\.NET CLR Memory(w3wp)\Gen 2 heap size
\.NET CLR Memory(w3wp)\Large Object Heap size
\.NET CLR Memory(w3wp#1)\% Time in GC
\.NET CLR LocksAndThreads(w3wp#1)\Total # of Contentions

**Comment by sschwartzman** [comment]
All of those are all in the default config.json, which I just reorganized to be easier to review and update:

Memory: https://github.com/newrelic/nri-perfmon/blob/master/nri-perfmon/config/config.json#L167
Locks and Threads: https://github.com/newrelic/nri-perfmon/blob/master/nri-perfmon/config/config.json#L153

**Comment by mvaanand** [comment]
Are these Perfmon Counters or WMI ?

**Comment by sschwartzman** [comment]
WMI - you can tell that because if they were Perfmon Counters, it'd say "PerfCounter" in the Provider for each section. These are tried-and-true counters that work well coming from WMI. If you want to re-write as PerfCounters, that's up to you.

**Comment by mvaanand** [comment]
I tried and i'm not sure what is wrong. Need your help. Attaching config.json. Please let me know what i'm doing wrong with the config.

[config.zip](https://github.com/newrelic/nri-perfmon/files/3946705/config.zip)

**Comment by sschwartzman** [comment]
Can you leave these as WMI counters? They should work fine and will save you time of trying to replicate.

**Comment by mvaanand** [comment]
Will work with the WMI counters. Thanks Seth.

**Comment by sschwartzman** [comment]
For what it's worth, I dumped your config file exactly as written into my test Win10 server and it worked perfectly. Attached is the output I got.

[perfcounter-test.txt](https://github.com/newrelic/nri-perfmon/files/3946783/perfcounter-test.txt)
I'd still recommend using the original (WMI) version of config.json, since it's the default used by all other users of the Perfmon OHI and works very well. If it's not reporting back the counters you expect, then you can play with the PerfCounters.

**Comment by mvaanand** [comment]
The problem I saw was when I ran the NRQL in NR. It was returning an error.
Seemed like it couldnt recognize the _NET_CLR_Memory
or _NET_CLR_LocksAndThreads even though these appear under custom events.

Thanks,

Vijay Anand Manjamuthu.

*VCM IT - **DEVOPS* *-* *R**etail **A**pplication **S**upport.*

RAS ALL (ras.all@verizon.com) – 24x7

**Comment by sschwartzman** [comment]
Try putting them in backticks (`) like this:

```
SELECT count(*) FROM `_NET_CLR_LocksAndThreads` SINCE 30 MINUTES AGO
```

**Comment by mvaanand** [comment]
It worked. Thanks Much Seth. Pleasure working with you.

Thanks,

Vijay Anand Manjamuthu.

*VCM IT - **DEVOPS* *-* *R**etail **A**pplication **S**upport.*

RAS ALL (ras.all@verizon.com) – 24x7
